# sensors:
#   - default_sensor
#   - kinect_depthimage
# default_sensor:
#   far_clipping_plane_distance: 5.0
#   filtered_cloud_topic: filtered_cloud
#   image_topic: /head_mount_kinect/depth_registered/image_raw
#   max_update_rate: 1.0
#   near_clipping_plane_distance: 0.3
#   padding_offset: 0.03
#   padding_scale: 4.0
#   queue_size: 5
#   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#   shadow_threshold: 0.2
# kinect_depthimage:
#   far_clipping_plane_distance: 5.0
#   filtered_cloud_topic: filtered_cloud
#   image_topic: /head_mount_kinect/depth_registered/image_raw
#   max_update_rate: 1.0
#   near_clipping_plane_distance: 0.3
#   padding_offset: 0.03
#   padding_scale: 4.0
#   queue_size: 5
#   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#   shadow_threshold: 0.2
sensors:
  - kinect_depthimage

kinect_depthimage:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /head_mount_kinect/depth_registered/image_raw
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 4.0
  padding_offset: 0.03
  max_update_rate: 1.0
  filtered_cloud_topic: filtered_cloud
